#!/usr/bin/env python3
"""Rasterize the bundled Bootstrap Icons SVGs for the E1003 panel."""

import argparse
import hashlib
from io import BytesIO
from pathlib import Path

import cairosvg
from PIL import Image


ROOT = Path(__file__).parent
ICONS = (
    "sun-fill", "moon-fill", "cloud-sun-fill", "cloud-moon-fill",
    "cloud-fill", "cloud-drizzle-fill", "cloud-rain-fill",
    "cloud-rain-heavy-fill",
)
SIZE = 42  # 18 logical pixels at the E1003's 2.34x panel scale.


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    sources = [(name, (ROOT / "bootstrap_svg" / f"{name}.svg").read_bytes())
               for name in ICONS]
    digest = hashlib.sha256(str(SIZE).encode())
    for name, svg in sources:
        digest.update(name.encode())
        digest.update(svg)
    lines = [
        "#pragma once", "#include <stdint.h>", "",
        "/* Generated by generate_native_weather_icons.py; do not edit. */",
        f"/* Bootstrap Icons (MIT); E1003 source sha256={digest.hexdigest()}. */",
    ]
    for name, svg in sources:
        png = cairosvg.svg2png(bytestring=svg, output_width=SIZE, output_height=SIZE)
        alpha = Image.open(BytesIO(png)).convert("RGBA").getchannel("A").tobytes()
        symbol = "BOOTSTRAP_" + name.removesuffix("-fill").upper().replace("-", "_") + "_42"
        lines.append(f"static const uint8_t {symbol}[{SIZE * SIZE}] = {{")
        for start in range(0, len(alpha), 16):
            lines.append("    " + ", ".join(str(value) for value in alpha[start:start + 16]) + ",")
        lines.extend(("};", ""))
    output = ROOT.parent / "bootstrap_weather_icons_native.h"
    generated = "\n".join(lines)
    if args.check:
        if output.read_text() != generated:
            parser.error(f"{output} is stale; regenerate it")
    else:
        output.write_text(generated)


if __name__ == "__main__":
    main()
